MODEL:
  TYPE: qformer_fast
  NAME: qformer_fast_base_patch4_window7_224
  DROP_PATH_RATE: 0.55
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 7
  QuadrangleAttention:
    rpe: 'v1'
TRAIN:
  coords_lambda: 5e-1