MODEL:
  TYPE: qformer
  NAME: qformer_small_patch4_window7_224
  DROP_PATH_RATE: 0.3
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 7
  QuadrangleAttention:
    rpe: 'v1'
TRAIN:
  coords_lambda: 0.1